### ISSUE TITLE
airframe-http-codegen: complex object parameter should be optional if the default value is defined

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#2149]
model class:
```scala
case class SubmitQueryRequest(query:String, params:Map[String, Any]=Map.empty, ulid:ULID = ULID.newULID)
```

Generated openapi.yaml:
```
components:
  schemas:
    SubmitQueryRequest:
      type: object
      required:
        - query
        - params <<-- this should not be here
        - ulid << -- this should not be here
      properties:
        query:
          type: string
        params:
          type: object
          additionalProperties:
            type: string
        ulid:
          type: object
          required:
            - ulid
          properties:
            ulid:
              type: string
```
