### ISSUE TITLE
[airframe-config] Overriding doesn't work for nested properties

### ISSUE THREAD

**Issue by takezoe** [wvlet/airframe#273]
For example, assuming we have following config and case classes:

```yaml
default: &default
  file:
    name: access.log
    maxFileSize: 20

development:
  <<: *default
  file:
    maxFileSize: 5
```

```scala
case class LogConfig(file: LogFileConfig)
case class LogFileConfig(file: String, maxFileSize: Int)
```

I expect `maxFileSize` is overriden and `name` is `"access.log"` in development environment, but actually `name` is empty. It's also empty even if it has a default argument in the case class.

I guess overriding works for only top level properties, but it would be nice if it works for nested properties as well.

**Comment by xerial** [comment]
@takezoe It looks like this behavior is coming from the inheritance of YAML format:
https://stackoverflow.com/questions/14184971/more-complex-inheritance-in-yaml

**Comment by xerial** [comment]
To override nested config parameters, the YAML file looks like this:
```
default: &default
  file: &file_default
    name: access.log
    maxFileSize: 20

development:
  <<: *default
  file:
    <<: *file_default
    maxFileSize: 5
```
